#!/usr/bin/python2
########################################################################################################
##Copyright (C) 2017 Abhiram Shibu                                                                    ## ##                                                                                                    ##
##                                                                                                    ##
##This program is free software; you can redistribute it and/or modify it under the terms of the GNU  ##
##General Public License as published by the Free Software Foundation; with version 2 of the          ##
##License.                                                                                            ##
##                                                                                                    ##
##This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   ##
##even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       ##
##General Public License for more details.                                                            ##
##                                                                                                    ##
##You should have received a copy of the GNU General Public License along with this program; if not,  ##
##write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  ##
########################################################################################################
import time
import subprocess
import os
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
def init():
	check=1
	c=0
	cpuinfo_file=os.popen("cat /proc/cpuinfo").read()
	cpuinfo_file=cpuinfo_file.split("\n")
	cpuinfo_get=['vendor_id','model name','cpu MHz','cache size']
	tmp=[]
	a=cpuinfo_file[0]	
	a=a.replace("\t"," ")
	a=a.replace(":"," ").split()
	z=0
	for i in cpuinfo_file:
		if a[0] in i:
			z+=1
		if z==2:
			break
		tmp.append(i)
	cpuinfo_file=tmp
	dic={}
	for i in range(30):
		cols=int(os.popen("tput cols").read().strip())	
		os.system('clear');
		print bcolors.HEADER+"I am SYSz".center(cols)+bcolors.ENDC
		print "Checking system requirements ",
		if(i<len(cpuinfo_get)):
			for z in cpuinfo_file:
				if cpuinfo_get[i] in z :
					z=z.replace(cpuinfo_get[i],' ')
					z=z.replace("\t"," ")
					z=z.replace(":"," ").strip()
					key=cpuinfo_get[i]
					dic[key]=z
					print key + "=>" + z + " ",
					
		if(c==0):
			print "-"
			c+=1
		elif(c==1):
			print "\\"
			c+=1
		elif(c==2):
			print "|"
			c+=1
		else:
			print "/"
			c=0
		time.sleep(0.2)
	return(cpuinfo_get,dic)
keys,cpu=init()
print cpu

def read_status():
    """
    This function reads the output of your command, finds the line with
    'percentage' (line 17, where first line = 0) and reads the figure
    """
    command = "upower -i $(upower -e | grep BAT) | grep --color=never -E percentage|xargs|cut -d' ' -f2|sed s/%//"
    get_batterydata = subprocess.Popen(["/bin/bash", "-c", command], stdout=subprocess.PIPE)
    return get_batterydata.communicate()[0].decode("utf-8").replace("\n", "")

charge = int(read_status())
print("Battery Charged :",charge,"%")

