#!/usr/bin/python2
########################################################################################################
##Copyright (C) 2017 Abhiram Shibu                                                                    ##                    
##                                                                                                    ##
##This program is free software; you can redistribute it and/or modify it under the terms of the GNU  ##
##General Public License as published by the Free Software Foundation; with version 2 of the          ##
##License.                                                                                            ##
##                                                                                                    ##
##This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without   ##
##even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU       ##
##General Public License for more details.                                                            ##
##                                                                                                    ##
##You should have received a copy of the GNU General Public License along with this program; if not,  ##
##write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  ##
########################################################################################################
import time
import os
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
def init():
	c=0
	for i in range(100):
		cols=int(os.popen("tput cols").read().strip())	
		os.system('clear');
		print bcolors.HEADER+"I am SYSz".center(cols)+bcolors.ENDC
		print "Checking system requirements ",
		if(c==0):
			print "-"
			c+=1
		elif(c==1):
			print "\\"
			c+=1
		elif(c==2):
			print "|"
			c+=1
		else:
			print "/"
			c=0
		time.sleep(0.2)
init()

