#!/usr/bin/python2
import time
import os
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
def init():
	c=0
	for i in range(100):
		cols=int(os.popen("tput cols").read().strip())	
		os.system('clear');
		print bcolors.HEADER+"I am SYSz".center(cols)+bcolors.ENDC
		print "Checking system requirements ",
		if(c==0):
			print "-"
			c+=1
		elif(c==1):
			print "\\"
			c+=1
		elif(c==2):
			print "|"
			c+=1
		else:
			print "/"
			c=0
		time.sleep(0.2)
init()

